name: semantic-search
channels:
  - conda-forge
dependencies:
  - python=3.*
  - numpy=1.*
  - pytorch=1.*
  - transformers=4.*
  - sentence-transformers=2.0.0
  - fastapi=0.*
  - uvicorn=0.*
  - pyyaml=5.*
  - pytest=6.*
  - pillow=8.*
  - torchvision=0.*